GET http://localhost:3004/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWhtYWQiLCJpYXQiOjE2MzM1MDIxMjh9.458hg_XeVlZ-zlwQ9GukPUmHwoGUPtVzsfsvNbKZAjI

### 

 POST http://localhost:4000/token
 Content-Type: application/json
 {
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWhtYWQiLCJpYXQiOjE2MzM1MDM3MTh9.88Qx8aY4m3xMze7Dcr6wWjSyiSmnTvtxZPAqMh909B0"     
 }

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"ahmad"
}